- main/buildout.cfg
- main/local_modules/main/__openerp__.py
> [#23][IMP] Replace base_phone by base_phone_validation.

- main/local_modules/portal_user/views/portal_items.xml
Remove the Messaging Menu from the backend top menu
> [#35][IMP] Remove the messaging menu on top bar.

- main/local_modules/main_data/__openerp__.py
- main/local_modules/main_data/security/ir.model.access.csv
> [#42][FIX] Fix the error 403 when a not logged user goes to home page.

- main/local_modules/portal_user/security/base_security.xml
> [#59][FIX] Fix the issue with doublon of a ir.rule.

- main/local_modules/main_data/views/geo_partner_view.xml
> [#48][IMP] Switch to openstreetmap.

- main/local_modules/shared_web_theme/static/src/css/_custom.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
Im chat = 10000
loading = 9000
Map = 100
> Z-index im chat

- main/local_modules/shared_web_theme/static/src/css/_custom.scss
- main/local_modules/shared_web_theme/static/src/css/_flatify.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
media queries for map size
best integration map in design
Fixed #92
> several design dashboard map

- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
update color text badge in advanced search
Fixed #106
> Text color selection

- main/local_modules/res_partner_location_validation/__openerp__.py
- main/local_modules/res_partner_location_validation/models/res_partner.py
- main/local_modules/res_partner_location_validation/tests/test_res_partner.py
- main/upgrade.py
> [#139][FIX] fix the issue with some address where city is not found.

- main/local_modules/res_partner_missing_details/__openerp__.py
- main/local_modules/res_partner_missing_details/ir_cron.xml
- main/local_modules/res_partner_missing_details/models/res_partner.py
> [#141][IMP] set the cron job to do 300 partners every 12hours.

- main/local_modules/res_partner_location_validation/__openerp__.py
- main/local_modules/res_partner_location_validation/models/res_partner.py
- main/local_modules/res_partner_location_validation/tests/test_res_partner.py
> Hotfix 145

- main/local_modules/res_partner_email_validation_missing_details/missing_details.xml
- main/local_modules/res_partner_location_validation_missing_details/missing_details.xml
- main/local_modules/res_partner_missing_details/models/res_partner.py
- main/local_modules/res_partner_missing_details/views/res_partner_view.xml
- main/local_modules/res_partner_phone_missing_details/missing_details.xml
- main/local_modules/res_partner_url_validation_missing_details/missing_details.xml
> #141 missing details

- main/local_modules/portal_user/__openerp__.py
- main/local_modules/portal_user/views/res_partner_view.xml
- main/local_modules/res_partner_social_networks/__openerp__.py
- main/local_modules/res_partner_social_networks/views/res_partner_views.xml
> [#151][IMP] Update the placeholder of the res.partner view

- main/buildout.cfg
- main/install.sh
- main/local_modules/shared_web_theme/static/src/css/_custom.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
> #155 geoengine

- main/local_modules/main_data/__openerp__.py
- main/local_modules/main_data/models/res_partner.py
> [#170][IMP] Set zip code as optional on res.partner.

- main/local_modules/main_data/__openerp__.py
- main/local_modules/main_data/data/res_groups_data.xml
> [#172][IMP] Add the public_user to group_user.

- main/local_modules/frontend/__openerp__.py
- main/local_modules/frontend/templates/login_template.xml
> [#164][IMP] restore the sign up page.

- main/buildout.cfg
- main/local_modules/frontend/templates/homepage.xml
- main/local_modules/shared_web_theme/static/src/css/_custom.scss
- main/local_modules/shared_web_theme/static/src/css/_homepage.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
- main/local_modules/shared_web_theme/static/src/css/base.scss
homepage colors and other stuff design
> 1st-design

- main/local_modules/res_partner_location_validation/__openerp__.py
- main/local_modules/res_partner_location_validation/models/res_partner.py
> [#116][FIX] Fix the bug when the db is init.

- main/local_modules/frontend/__openerp__.py
- main/local_modules/frontend/controllers/main.py
- main/local_modules/portal_user/__openerp__.py
- main/local_modules/portal_user/views/portal_items.xml
fix #178 
fix #177 
work on #188
> optimisation

- main/local_modules/main_data/__openerp__.py
- main/local_modules/main_data/data/website_menu.xml
- main/local_modules/portal_user/__openerp__.py
- main/local_modules/portal_user/views/website_menu.xml
> [#217][IMP] Review website.menu title.

- main/local_modules/portal_user/views/portal_items.xml
> [#232][IMP] add SIGGRAPH 2015 menu item

- main/local_modules/frontend/templates/events.xml
- main/local_modules/frontend/templates/homepage.xml
> 244 redundant grid class

- main/local_modules/frontend/__openerp__.py
- main/local_modules/frontend/templates/events.xml
- main/local_modules/frontend/templates/homepage.xml
> [#243][IMP] Add DOCTYPE at the head of the templates.

- main/local_modules/frontend/__openerp__.py
- main/local_modules/frontend/templates/events.xml
- main/local_modules/portal_user/__openerp__.py
- main/local_modules/portal_user/views/portal_items.xml
> [#255][IMP] Remove menus for SIGGRAPH2015.

- main/local_modules/frontend/__openerp__.py
- main/local_modules/frontend/templates/homepage.xml
> [#255][IMP] Remove a sentence referencing to siggraph in homepage.

- main/local_modules/frontend/templates/homepage.xml
- main/local_modules/shared_web_theme/static/src/css/_fonts.scss
- main/local_modules/shared_web_theme/static/src/css/_homepage.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
- more colorfull
- better responsive design
- best bold font instead of bold attribute in  label class
- suppr <em> attributes for label
> #227 Partner homepage

- main/local_modules/main/__openerp__.py
- main/local_modules/main_data/__openerp__.py
- main/local_modules/main_data/data/auditlog_res_partner.xml
> [#156][IMP] Create a rule for res.partner.

- main/buildout.cfg
- main/local_modules/frontend_reports/controllers/main.py
- main/local_modules/frontend_reports/static/js/line_chart_user.js
- main/local_modules/frontend_reports/static/js/linecharts.js
- main/local_modules/frontend_reports/static/js/piecharts.js
- main/local_modules/frontend_reports/templates/template_reports.xml
> 279 company by countries

- main/buildout.cfg
> [#296][IMP] buildout: add the unaccent option.

- main/local_modules/frontend_shop/__init__.py
- main/local_modules/frontend_shop/controllers/__init__.py
- main/local_modules/frontend_shop/controllers/main.py
- main/local_modules/frontend_shop/data/website_menus.xml
- main/local_modules/frontend_shop/templates/template_shop.xml
That will he[p to track the traffic to the shop.
work on #302
> [#302][IMP] frontend_shop: implement a page that goes to the shop

- main/local_modules/portal_user/views/res_partner_view.xml
- main/local_modules/res_partner_location_validation/models/res_partner.py
> Duplicated states

- main/local_modules/frontend/templates/homepage.xml
> [#307][IMP] frontend: update text on homepage.

- main/buildout.cfg
- main/local_modules/frontend/templates/homepage.xml
- main/local_modules/main/__openerp__.py
> 314 sentry

- main/local_modules/frontend/templates/homepage.xml
- main/local_modules/frontend_base/templates/template_engine.xml
- main/local_modules/frontend_base/templates/template_head.xml
> [#328][IMP] frontend_base: move the js and css blocks to engine.

- main/local_modules/frontend/templates/homepage.xml
- main/local_modules/frontend_base/templates/template_engine.xml
- main/local_modules/frontend_base/templates/template_head.xml
> [#328][IMP] frontend_base: css are loaded in the head.

- main/local_modules/frontend_base/models/__init__.py
- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_base/models/res_users.py
- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_homepage/controllers/homepage.py
- main/local_modules/frontend_homepage/templates/template_body.xml
> 319 frontend homepage

- main/local_modules/res_partner_social_networks/models/res_partner.py
- main/local_modules/res_partner_social_networks/views/res_partner_views.xml
work on #341 
* Facebook et Linkedin sont maintenant and la tab additional social network
* Youtube et Vimeo ont été rajoutés
* Les contraintes pour les urls ont été assouplient
* les messages d'erreurs guident plus
> 341 social networks

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_bootstraper.scss
- main/local_modules/shared_web_theme/static/src/css/_buttons.scss
- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/_main.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
- main/local_modules/shared_web_theme/static/src/css/base.scss
#367 : 
- better responsive way for  link in navbar
BT Login navbar
- change color
- custom outline buttons
- change dropdown style
#361 
- Position Counter in multiple size Fix
- change Counter size and position in Mobile view
- Position Map in mobile View (Portrait Paysage)
> #361 mobile high res

- main/local_modules/frontend/templates/login_template.xml
- main/local_modules/shared_web_theme/static/src/css/_super-backoffice.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
- alignement des forms 'log-in' 'signup'
- footer toujours en bas de page seulement sur ces pages
> 362-[FIX]-vertical-align-form

- main/etc/odoo_server.cfg
> odoo_server.cfg: use codega server dns

- main/local_modules/frontend_base/templates/template_engine.xml
> frontend_base: fix the url for google analytics.

- main/local_modules/frontend_base/templates/template_engine.xml
> frontend_base: review the google analytics template.

- main/local_modules/frontend_base/templates/template_body.xml
> frontend_base: add sign up in the join menu.

- main/local_modules/frontend_base/models/__init__.py
- main/local_modules/frontend_base/models/caches.py
- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_homepage/controllers/homepage.py
- main/local_modules/frontend_listing/controllers/listing.py
> frontend: set caches as reset when a company is updated.

- main/local_modules/frontend_base/controllers/base.py
- main/local_modules/frontend_base/static/src/js/counters.js
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/frontend_listing/static/src/js/directory.js
- main/local_modules/frontend_listing/templates/template_body.xml
> frontend_listing: add count of companies of the search.

- main/local_modules/frontend_base/models/res_partner.py
> frontend_base: res_partner.info_window encoding.

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_listing/static/src/css/frontend_listing.scss
fix the issue of scrolling mentioned in #361
> frontend_listing: set back the scrolling y

- main/local_modules/frontend_base/models/res_industry.py
- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_homepage/templates/template_body.xml
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/frontend_listing/templates/template_body.xml
> 416 filters

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_listing/templates/template_body.xml
> frontend_listing: different footers between list and map.

- main/local_modules/frontend_listing/controllers/listing.py
> frontend_listing: datadog metrics where inverted.

- main/local_modules/frontend_base/static/src/js/counters.js
> frontend_base.counters.js: remove console.log

- main/local_modules/frontend_listing/templates/template_body.xml
> frontend_listing: hiding add a studio button.

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_buttons.scss
- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/_main.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
> 433 bt user connect

- main/local_modules/frontend_base/templates/template_body.xml
> frontend_base: add 404

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_homepage/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_bootstraper.scss
- main/local_modules/shared_web_theme/static/src/css/_main.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
la font CGSM n'était pas déclaré a certains endroits.
quelques ajustements de taille aussi
> [FIX]font-cgsm

- main/local_modules/frontend_homepage/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_main.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
> 482 geochart height

- main/local_modules/frontend_base/templates/template_body.xml
> frontend_base: restore link of industries.

- main/local_modules/frontend_studio/controllers/studio.py
- main/local_modules/frontend_studio/templates/template_body.xml
> frontend_studio: same location link

- main/local_modules/frontend_studio/static/js/geocharts_marker.js
- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/frontend_studio/templates/template_engine.xml
> frontend_studio: implement geochart as header of the page.

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_listing/static/src/js/google_map.js
- main/local_modules/frontend_listing/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_colors.scss
> Fix directory listing map

- main/local_modules/frontend_homepage/controllers/homepage.py
> Number companie homepage

- main/local_modules/frontend_homepage/static/js/geocharts.js
> frontend_homepage: implement on click event on geochart.

- main/local_modules/frontend_listing/static/src/js/google_map.js
> frontend_listing: only one infowindow at the time.

- main/local_modules/frontend_homepage/templates/template_body.xml
> frontend_homepage: typo in title.

- main/local_modules/frontend_listing/static/src/js/directory.js
> [#534]sortable-column

- main/local_modules/frontend_listing/controllers/listing.py
> frontend_listing: swith to TTLCache and implement force_reset_cache.

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_bootstraper.scss
- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/_main.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
> [#544][FIX]mobil-nav

- .travis.yml
> Add codecov to travis.

- main/local_modules/frontend_base/static/src/js/a_submit.js
- main/local_modules/frontend_base/templates/template_engine.xml
> frontend_base: add the js to support the a-submit feature.

- main/local_modules/frontend_studio/__openerp__.py
- main/local_modules/frontend_studio/controllers/studio.py
- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
> frontend_studio: add edit template and field driven label names.

- main/local_modules/frontend_studio/templates/template_body.xml
> frontend_studio: add condition for the closed flag.

- main/local_modules/res_partner_social_networks/models/res_partner.py
- main/local_modules/res_partner_social_networks/tests/__init__.py
- main/local_modules/res_partner_social_networks/tests/test_res_partner.py
> res_partner_social_networks: fix bug with additional social networks.

- main/local_modules/shared_web_theme/web_theme.xml
> shared_web_theme: remove effect on backoffice.

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_studio/controllers/studio.py
- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
> 526 social network order

- main/local_modules/shared_web_theme/static/src/css/_bootstraper.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
Fix #570 
Pas de milestome, ça peut être poussé n'importe quand.
> [#570][FIX]navbar-responsive

- main/local_modules/frontend_studio/static/css/studio.css
- main/local_modules/frontend_studio/templates/template_body.xml
> [#539][FIX]zindex-geochart-studiodetails

- main/local_modules/frontend_studio/static/css/studio.css
> [#567][FIX]clean-navSearch

- main/local_modules/frontend_studio/static/css/studio-edit.css
- main/local_modules/frontend_studio/static/js/studio-edit.js
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
> 578 new design studio edit

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
> [FIX][#592]mobile-navdirectory

- main/local_modules/frontend_studio/static/css/studio-edit.css
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
Fix #604 
Surveiller comment le merge se passe 
Attention aux screenshots
> 604 edit studio

- main/local_modules/frontend_listing/templates/template_body.xml
- main/local_modules/frontend_studio/__openerp__.py
- main/local_modules/frontend_studio/controllers/studio.py
- main/local_modules/frontend_studio/models/res_partner.py
- main/local_modules/frontend_studio/static/js/form_validations.js
- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
- main/local_modules/frontend_studio/tests/__init__.py
- main/local_modules/frontend_studio/tests/test_res_partner_edition.py
> 566 page create

- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
> [FIX][#617]social-vimeo-color

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- mise en place de la font-regular pour les pays
- alignement vertical meilleur sur l'ensemble de la ligne
- espacement des lettres du pays et de la ville corrigé.
FIX #603
> [FIX][#603]minor-design-tables

- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_base/tests/test_res_partner.py
- main/local_modules/res_partner_social_networks/tests/test_res_partner.py
* make sure the header of the infowindow goes to the studio url
* solidify the code of location_code
work on #624
> frontend_base: update of res.partner methods

- main/local_modules/frontend_studio/static/css/studio.css
> 627 icon search

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
> 616 nav filters

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_listing/templates/template_body.xml
> [FIX][#621]admin-toolbox

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_studio/controllers/studio.py
> 631 page argument

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
> [FIX][#638]infoswindows-studio-link-name

- main/local_modules/res_partner_moderator_supervision/res_partner.py
> 640 slack log

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_studio/static/css/studio.css
- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/_main.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
#529 
Seulement dans la fiche studio.
> 529 design closed studio

- main/local_modules/frontend_studio/templates/template_body.xml
> frontend_studio: marqueePlus allows to go to specific tab.

- main/local_modules/frontend/__openerp__.py
- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_base/tests/test_res_partner.py
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/frontend_listing/templates/template_body.xml
- main/local_modules/frontend_studio/models/res_partner.py
> 613 remove beta testing

- main/local_modules/frontend_studio/static/css/studio-edit.css
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
> 646 edit industries design

- main/local_modules/frontend_studio/static/css/studio-edit.css
- main/local_modules/frontend_studio/templates/template_body_edit_mode.xml
> 655 edit nav bar

- main/local_modules/frontend_studio/models/res_partner.py
- main/local_modules/frontend_studio/tests/__init__.py
- main/local_modules/frontend_studio/tests/test_res_partner_location.py
> frontend_studio: ensure the zip code in the address in the studio page.

- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/js/main.js
> 674 link target

- main/local_modules/frontend_studio/static/css/studio.css
- main/local_modules/frontend_studio/templates/template_body.xml
> 644 flag options

- main/local_modules/frontend_studio/controllers/studio.py
- main/local_modules/frontend_studio/models/res_partner.py
- main/local_modules/frontend_studio/tests/__init__.py
- main/local_modules/frontend_studio/tests/test_res_partner_edition.py
- main/local_modules/frontend_studio/tests/test_res_partner_get_studios.py
- main/local_modules/frontend_studio/tests/test_res_partner_location.py
- main/local_modules/frontend_studio/tests/test_res_partner_save.py
> frontend_studio: store the number of visit of studios

- main/local_modules/frontend_base/controllers/base.py
- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_homepage/controllers/homepage.py
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/frontend_listing/templates/template_body.xml
* Set SearchDomain class that represents the domain of a search but also
the paramters
* add latest_modified filter
* add latest_created filter
* update the template
work on #687
> frontend: set up latest modified/created filters

- main/local_modules/shared_web_theme/static/src/css/_homepage.scss
> fix-logo-align

- main/local_modules/shared_web_theme/static/src/css/_colors.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
> fix-color-navbar-responsive

- main/local_modules/frontend_base/controllers/base.py
- main/local_modules/frontend_base/models/res_industry.py
- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_base/tests/test_res_partner.py
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/frontend_listing/models/res_partner.py
> optimization of the request for the map

- main/local_modules/frontend_homepage/templates/template_body.xml
Met en place d'une nouvelle phrase d'accroche.
> frontend_homepage: review of the catch phrase.

- main/local_modules/shared_web_theme/static/src/css/_main.scss
#731 DONE
error syntax
micro erreur qui ne faisait pas marcher mon 1er correctif #711 
ma faute :(
> error syntax Fix logo align

- main/local_modules/frontend_listing/controllers/listing.py
The server was crashing ig the partners was empty.
work on #733
> frontend_listing: solve the problem when result is empty

- main/local_modules/frontend_studio/controllers/studio.py
- main/local_modules/frontend_studio/templates/template_body.xml
The route for the action was not defined.
work on #722
> frontend_studio: manage the page flagged_closed

- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/frontend_listing/models/res_partner.py
- main/local_modules/frontend_listing/security/ir.model.access.csv
- main/local_modules/website_iframe_host/data/website_iframe_host_data.xml
- main/local_modules/website_iframe_host/security/ir.model.access.csv
Résoud le bug dans lequel les partenaires ne sont pas affichés si le state ou l'industrie n'etait pas renseigné.
Résoud aussi le probleme si les coordonnée geo ne sont pas rentré.
pas de tests implementé tho :(
> Frontend listing optionals in query

- main/local_modules/frontend_listing/static/src/css/bootstrap-table.css
- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_listing/static/src/js/directory.js
- main/local_modules/frontend_listing/templates/template_body.xml
> 743-updates-design

- main/local_modules/res_partner_moderator_supervision/res_partner.py
- main/local_modules/res_partner_moderator_supervision/tests/test_res_partner.py
* write triggers the slack log only if the update is done by someone
that is not moderator of cgstudiomap
* use config file for the webhook url instead of environment.
> res_partner_moderator_supervision: review of write

- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_listing/__openerp__.py
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/website_iframe_host/__openerp__.py
- main/local_modules/website_iframe_host/controllers/base.py
- main/local_modules/website_iframe_host/models/res_partner.py
- main/local_modules/website_iframe_host/tests/__init__.py
- main/local_modules/website_iframe_host/tests/test_res_partner.py
- main/local_modules/website_iframe_host/tests/test_website_iframe_host.py
> website.iframe.host: implement get_host_from_session

- main/local_modules/frontend_base/models/res_partner.py
- main/local_modules/frontend_listing/__openerp__.py
- main/local_modules/frontend_listing/controllers/listing.py
- main/local_modules/website_iframe_host/__openerp__.py
- main/local_modules/website_iframe_host/controllers/base.py
- main/local_modules/website_iframe_host/models/res_partner.py
- main/local_modules/website_iframe_host/tests/__init__.py
- main/local_modules/website_iframe_host/tests/test_res_partner.py
- main/local_modules/website_iframe_host/tests/test_website_iframe_host.py
* website.iframe.host: implement get_host_from_session (#760)
> Mise en production

- main/local_modules/website_iframe_host/controllers/base.py
- main/local_modules/website_iframe_host/tests/test_website_iframe_host.py
> website_iframe_host: set special fallback for google as referrer

- main/local_modules/frontend_homepage/static/css/homepage.css
cursor mouse interaction with pointer 
@foutoucour pas de screenshot. la touche print screen ne prend pas le curseur qui doit être le "pointeur main"
> add-cursor-mouse

- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_studio/static/css/studio.css
- main/local_modules/frontend_studio/templates/template_body.xml
- main/local_modules/shared_web_theme/static/src/css/_bootstraper.scss
- main/local_modules/shared_web_theme/static/src/css/base.css
- Mise à jour de la page Studio 
- Correction graphique de la navbar en mobile qui caché la barre de filtre
- Correction des nouvelles fonts et ajustements des tailles
- Correction des positions en fonction de la navbar moins haute
> 783 fix navbar influence

- main/local_modules/frontend_listing/static/src/css/bootstrap-table.css
- main/local_modules/frontend_listing/static/src/css/frontend_listing.css
- main/local_modules/frontend_listing/static/src/js/directory.js
- main/local_modules/frontend_listing/static/src/js/google_map.js
- main/local_modules/frontend_listing/static/src/lib/bootstrap-table-locale-all.js
- main/local_modules/frontend_listing/static/src/lib/bootstrap-table-mobile.js
- main/local_modules/frontend_listing/static/src/lib/bootstrap-table.js
La correction est plutôt basique visuellement. Par contre j'en ai profiter pour mettre certaines librairies qui gère le listing. Du coup après y'a du FIX pour revenir à ce que c'était avant la mise à jour.
le FOOTER : 
l'infowindows #441  qui trainait avec du debug de click and close.
> 780 map homepage

- main/local_modules/res_partner_location_validation/models/res_partner.py
- main/local_modules/res_partner_location_validation/tests/test_res_partner_addresses.py
> res_partner_location_validation: use long name to find states #791

- main/local_modules/frontend_base/models/res_industry.py
- main/local_modules/frontend_base/tests/__init__.py
- main/local_modules/frontend_base/tests/test_res_industry.py
> frontend_base: fix the url of tags in listing (#800)

- main/local_modules/frontend_base/templates/template_body.xml
- main/local_modules/frontend_link_to_dashboard/template_body.xml
> 786 dashboard locate

- main/local_modules/frontend_studio/static/css/studio-save.css
- main/local_modules/frontend_studio/templates/template_body.xml
> fix-influence-new-navbar
